language: php

dist: trusty

sudo: false

php:
    - '7.2'
    - '7.3'

cache:
    directories:
        - ~/.composer/cache/files

install:
    - composer install --no-interaction --prefer-dist

script:
    - composer validate --strict
    - composer normalize --dry-run
    - composer check-style
    - composer analyse
    - composer test
